import { http, HttpResponse } from 'msw'
import { allTopics, db } from '../db'
import { filterTickets, latency, serializeSearchParams } from '../utils'
import type { CountWithUrlSearchParams, TicketFilterType } from '@/types/api'

const V1 = '*/v1'

export const reportHandlers = [
  http.get(`${V1}/reports/summary`, async ({ request }) => {
    await latency()
    const url = new URL(request.url)
    const since = url.searchParams.get('since')
    const until = url.searchParams.get('until')

    const from = since ? new Date(Number(since) * 1000) : new Date(Date.now() - 7 * 86_400_000)
    const to = until ? new Date(Number(until) * 1000) : new Date()
    to.setHours(23, 59, 59, 999)

    const inRange = filterTickets(db.tickets, { from, until: to })

    const count = (viewIds: TicketFilterType[]): CountWithUrlSearchParams => ({
      count: filterTickets(inRange, { viewIds }).length,
      urlSearchParams: serializeSearchParams({ viewIds, from, until: to }),
    })

    const topicFeedback = inRange.flatMap((ticket) =>
      ticket.cards.filter((card) => card.feedback.saved)
    )
    const workflowFeedback = inRange.flatMap((ticket) =>
      ticket.executedWorkflows.filter((executed) => executed.feedback.saved)
    )
    const draftFeedback = inRange.flatMap((ticket) =>
      ticket.drafts.filter((draft) => draft.feedback.saved)
    )

    const feedbackCount = (total: number, view: TicketFilterType): CountWithUrlSearchParams => ({
      count: total,
      urlSearchParams: serializeSearchParams({ viewIds: [view], from, until: to }),
    })

    const topicRows = allTopics()
      .map((topic) => {
        const matching = inRange.filter((ticket) =>
          ticket.cards.some((card) => card.id === topic.id)
        )
        const feedback = matching.flatMap((ticket) =>
          ticket.cards.filter((card) => card.id === topic.id && card.feedback.saved)
        )
        return {
          id: topic.id,
          name: topic.name,
          emoji: topic.emoji,
          ticketsCount: matching.length,
          positiveFeedbackCount: feedback.filter((card) => card.feedback.savedPositive).length,
          negativeFeedbackCount: feedback.filter((card) => !card.feedback.savedPositive).length,
          parent: {
            id: topic.subCategoryId,
            name: topic.subCategoryName,
            parent: {
              id: topic.categoryId,
              name: topic.categoryName,
              color: topic.categoryColor,
            },
          },
        }
      })
      .sort((a, b) => b.ticketsCount - a.ticketsCount)

    return HttpResponse.json({
      countsWithUrlSearchParams: {
        conversations: {
          count: inRange.length,
          urlSearchParams: serializeSearchParams({ from, until: to }),
        },
        eligibleConversations: count(['ELIGIBLE']),
        conversationsWithTopic: count(['ELIGIBLE', 'ANY_TOPIC']),
        conversationsWithNoTopic: count(['ELIGIBLE', 'NO_TOPIC']),
        conversationsWithWorkflowExecuted: count(['ELIGIBLE', 'ANY_WORKFLOW_ACTION_EXECUTED']),
        conversationsWithWorkflowTextMacroExecuted: count([
          'ELIGIBLE',
          'ANY_WORKFLOW_TEXT_ACTION_EXECUTED',
        ]),
        conversationsWithWorkflowNonTextMacroExecuted: count([
          'ELIGIBLE',
          'ANY_WORKFLOW_NON_TEXT_ACTION_EXECUTED',
        ]),
        conversationsWithWorkflowMacroSuggestionUsed: count([
          'ELIGIBLE',
          'ANY_WORKFLOW_ACTION_SUGGESTION_USED',
        ]),
        conversationsWithWorkflowMacroSuggested: count([
          'ELIGIBLE',
          'ANY_WORKFLOW_ACTION_SUGGESTED',
        ]),
        conversationsWithDraftInserted: count(['ELIGIBLE', 'DRAFT_INSERTED']),
        conversationsWithDraftNotInserted: count(['ELIGIBLE', 'DRAFT_NOT_INSERTED']),
        conversationsWithDraftAutoGenerated: count(['ELIGIBLE', 'DRAFT_AUTOMATICALLY_GENERATED']),
        conversationsWithDraftManuallyGenerated: count(['ELIGIBLE', 'DRAFT_MANUALLY_GENERATED']),
        topicsPositiveFeedback: feedbackCount(
          topicFeedback.filter((card) => card.feedback.savedPositive).length,
          'TOPIC_POSITIVE_FEEDBACK'
        ),
        topicsNegativeFeedback: feedbackCount(
          topicFeedback.filter((card) => !card.feedback.savedPositive).length,
          'TOPIC_NEGATIVE_FEEDBACK'
        ),
        workflowsPositiveFeedback: feedbackCount(
          workflowFeedback.filter((executed) => executed.feedback.savedPass).length,
          'WORKFLOW_POSITIVE_FEEDBACK'
        ),
        workflowsNegativeFeedback: feedbackCount(
          workflowFeedback.filter((executed) => !executed.feedback.savedPass).length,
          'WORKFLOW_NEGATIVE_FEEDBACK'
        ),
        draftsPositiveFeedback: feedbackCount(
          draftFeedback.filter((draft) => draft.feedback.savedGood).length,
          'DRAFT_POSITIVE_FEEDBACK'
        ),
        draftsNegativeFeedback: feedbackCount(
          draftFeedback.filter((draft) => !draft.feedback.savedGood).length,
          'DRAFT_NEGATIVE_FEEDBACK'
        ),
      },
      topics: topicRows,
      topicsDetected: inRange.reduce((total, ticket) => total + ticket.cards.length, 0),
      workflowsTriggered: inRange.reduce(
        (total, ticket) => total + ticket.executedWorkflows.length,
        0
      ),
      draftsGenerated: inRange.reduce((total, ticket) => total + ticket.drafts.length, 0),
    })
  }),
]
