/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountManagementRouteImport } from './routes/account-management'
import { Route as StartRouteImport } from './routes/start'
import { Route as AuthJoinRouteImport } from './routes/_auth/join'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTopicsRouteImport } from './routes/_authenticated/topics'
import { Route as AuthSlugRouteImport } from './routes/auth/$slug'
import { Route as AuthLoginWidgetRouteImport } from './routes/_auth/login_.widget'
import { Route as AuthPasswordForgotRouteImport } from './routes/_auth/password.forgot'
import { Route as AuthPasswordResetRouteImport } from './routes/_auth/password.reset'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents/$agentId'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents/new'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations/index'
import { Route as AuthenticatedIntegrationsSlugRouteImport } from './routes/_authenticated/integrations/$slug'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge/index'
import { Route as AuthenticatedKnowledgeBusinessInformationRouteImport } from './routes/_authenticated/knowledge/business-information'
import { Route as AuthenticatedScenariosIndexRouteImport } from './routes/_authenticated/scenarios/index'
import { Route as AuthenticatedScenariosMacrosRouteImport } from './routes/_authenticated/scenarios/macros'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAgentPanelRouteImport } from './routes/_authenticated/settings/agent-panel'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedIntegrationsFrontInboxesRouteImport } from './routes/_authenticated/integrations/front/inboxes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountManagementRoute = AccountManagementRouteImport.update({
  id: '/account-management',
  path: '/account-management',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJoinRoute = AuthJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsRoute = AuthenticatedTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSlugRoute = AuthSlugRouteImport.update({
  id: '/auth/$slug',
  path: '/auth/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginWidgetRoute = AuthLoginWidgetRouteImport.update({
  id: '/login_/widget',
  path: '/login/widget',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPasswordForgotRoute = AuthPasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsSlugRoute =
  AuthenticatedIntegrationsSlugRouteImport.update({
    id: '/integrations/$slug',
    path: '/integrations/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeBusinessInformationRoute =
  AuthenticatedKnowledgeBusinessInformationRouteImport.update({
    id: '/knowledge/business-information',
    path: '/knowledge/business-information',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenariosIndexRoute =
  AuthenticatedScenariosIndexRouteImport.update({
    id: '/scenarios/',
    path: '/scenarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenariosMacrosRoute =
  AuthenticatedScenariosMacrosRouteImport.update({
    id: '/scenarios/macros',
    path: '/scenarios/macros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAgentPanelRoute =
  AuthenticatedSettingsAgentPanelRouteImport.update({
    id: '/settings/agent-panel',
    path: '/settings/agent-panel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsFrontInboxesRoute =
  AuthenticatedIntegrationsFrontInboxesRouteImport.update({
    id: '/integrations/front/inboxes',
    path: '/integrations/front/inboxes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-management': typeof AccountManagementRoute
  '/start': typeof StartRoute
  '/join': typeof AuthJoinRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/auth/$slug': typeof AuthSlugRoute
  '/login/widget': typeof AuthLoginWidgetRoute
  '/password/forgot': typeof AuthPasswordForgotRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/integrations/$slug': typeof AuthenticatedIntegrationsSlugRoute
  '/knowledge/business-information': typeof AuthenticatedKnowledgeBusinessInformationRoute
  '/scenarios/macros': typeof AuthenticatedScenariosMacrosRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/agent-panel': typeof AuthenticatedSettingsAgentPanelRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/scenarios/': typeof AuthenticatedScenariosIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/integrations/front/inboxes': typeof AuthenticatedIntegrationsFrontInboxesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-management': typeof AccountManagementRoute
  '/start': typeof StartRoute
  '/join': typeof AuthJoinRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/auth/$slug': typeof AuthSlugRoute
  '/login/widget': typeof AuthLoginWidgetRoute
  '/password/forgot': typeof AuthPasswordForgotRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/integrations/$slug': typeof AuthenticatedIntegrationsSlugRoute
  '/knowledge/business-information': typeof AuthenticatedKnowledgeBusinessInformationRoute
  '/scenarios/macros': typeof AuthenticatedScenariosMacrosRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/agent-panel': typeof AuthenticatedSettingsAgentPanelRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/scenarios': typeof AuthenticatedScenariosIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/integrations/front/inboxes': typeof AuthenticatedIntegrationsFrontInboxesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account-management': typeof AccountManagementRoute
  '/start': typeof StartRoute
  '/_auth/join': typeof AuthJoinRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/topics': typeof AuthenticatedTopicsRoute
  '/auth/$slug': typeof AuthSlugRoute
  '/_auth/login_/widget': typeof AuthLoginWidgetRoute
  '/_auth/password/forgot': typeof AuthPasswordForgotRoute
  '/_auth/password/reset': typeof AuthPasswordResetRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/integrations/$slug': typeof AuthenticatedIntegrationsSlugRoute
  '/_authenticated/knowledge/business-information': typeof AuthenticatedKnowledgeBusinessInformationRoute
  '/_authenticated/scenarios/macros': typeof AuthenticatedScenariosMacrosRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/agent-panel': typeof AuthenticatedSettingsAgentPanelRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/scenarios/': typeof AuthenticatedScenariosIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/integrations/front/inboxes': typeof AuthenticatedIntegrationsFrontInboxesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-management'
    | '/start'
    | '/join'
    | '/login'
    | '/register'
    | '/conversations'
    | '/home'
    | '/reports'
    | '/team'
    | '/topics'
    | '/auth/$slug'
    | '/login/widget'
    | '/password/forgot'
    | '/password/reset'
    | '/agents/$agentId'
    | '/agents/new'
    | '/integrations/$slug'
    | '/knowledge/business-information'
    | '/scenarios/macros'
    | '/settings/account'
    | '/settings/agent-panel'
    | '/settings/billing'
    | '/settings/notifications'
    | '/agents/'
    | '/integrations/'
    | '/knowledge/'
    | '/scenarios/'
    | '/settings/'
    | '/integrations/front/inboxes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-management'
    | '/start'
    | '/join'
    | '/login'
    | '/register'
    | '/conversations'
    | '/home'
    | '/reports'
    | '/team'
    | '/topics'
    | '/auth/$slug'
    | '/login/widget'
    | '/password/forgot'
    | '/password/reset'
    | '/agents/$agentId'
    | '/agents/new'
    | '/integrations/$slug'
    | '/knowledge/business-information'
    | '/scenarios/macros'
    | '/settings/account'
    | '/settings/agent-panel'
    | '/settings/billing'
    | '/settings/notifications'
    | '/agents'
    | '/integrations'
    | '/knowledge'
    | '/scenarios'
    | '/settings'
    | '/integrations/front/inboxes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/account-management'
    | '/start'
    | '/_auth/join'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/conversations'
    | '/_authenticated/home'
    | '/_authenticated/reports'
    | '/_authenticated/team'
    | '/_authenticated/topics'
    | '/auth/$slug'
    | '/_auth/login_/widget'
    | '/_auth/password/forgot'
    | '/_auth/password/reset'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/agents/new'
    | '/_authenticated/integrations/$slug'
    | '/_authenticated/knowledge/business-information'
    | '/_authenticated/scenarios/macros'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/agent-panel'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/agents/'
    | '/_authenticated/integrations/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/scenarios/'
    | '/_authenticated/settings/'
    | '/_authenticated/integrations/front/inboxes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountManagementRoute: typeof AccountManagementRoute
  StartRoute: typeof StartRoute
  AuthSlugRoute: typeof AuthSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-management': {
      id: '/account-management'
      path: '/account-management'
      fullPath: '/account-management'
      preLoaderRoute: typeof AccountManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/join': {
      id: '/_auth/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthJoinRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics': {
      id: '/_authenticated/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthenticatedTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/$slug': {
      id: '/auth/$slug'
      path: '/auth/$slug'
      fullPath: '/auth/$slug'
      preLoaderRoute: typeof AuthSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login_/widget': {
      id: '/_auth/login_/widget'
      path: '/login/widget'
      fullPath: '/login/widget'
      preLoaderRoute: typeof AuthLoginWidgetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/password/forgot': {
      id: '/_auth/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof AuthPasswordForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/password/reset': {
      id: '/_auth/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations/$slug': {
      id: '/_authenticated/integrations/$slug'
      path: '/integrations/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof AuthenticatedIntegrationsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/business-information': {
      id: '/_authenticated/knowledge/business-information'
      path: '/knowledge/business-information'
      fullPath: '/knowledge/business-information'
      preLoaderRoute: typeof AuthenticatedKnowledgeBusinessInformationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios/': {
      id: '/_authenticated/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof AuthenticatedScenariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios/macros': {
      id: '/_authenticated/scenarios/macros'
      path: '/scenarios/macros'
      fullPath: '/scenarios/macros'
      preLoaderRoute: typeof AuthenticatedScenariosMacrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/agent-panel': {
      id: '/_authenticated/settings/agent-panel'
      path: '/settings/agent-panel'
      fullPath: '/settings/agent-panel'
      preLoaderRoute: typeof AuthenticatedSettingsAgentPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations/front/inboxes': {
      id: '/_authenticated/integrations/front/inboxes'
      path: '/integrations/front/inboxes'
      fullPath: '/integrations/front/inboxes'
      preLoaderRoute: typeof AuthenticatedIntegrationsFrontInboxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthJoinRoute: typeof AuthJoinRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthLoginWidgetRoute: typeof AuthLoginWidgetRoute
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthJoinRoute: AuthJoinRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthLoginWidgetRoute: AuthLoginWidgetRoute,
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTopicsRoute: typeof AuthenticatedTopicsRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
  AuthenticatedIntegrationsSlugRoute: typeof AuthenticatedIntegrationsSlugRoute
  AuthenticatedKnowledgeBusinessInformationRoute: typeof AuthenticatedKnowledgeBusinessInformationRoute
  AuthenticatedScenariosMacrosRoute: typeof AuthenticatedScenariosMacrosRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAgentPanelRoute: typeof AuthenticatedSettingsAgentPanelRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedScenariosIndexRoute: typeof AuthenticatedScenariosIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedIntegrationsFrontInboxesRoute: typeof AuthenticatedIntegrationsFrontInboxesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTopicsRoute: AuthenticatedTopicsRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
  AuthenticatedIntegrationsSlugRoute: AuthenticatedIntegrationsSlugRoute,
  AuthenticatedKnowledgeBusinessInformationRoute:
    AuthenticatedKnowledgeBusinessInformationRoute,
  AuthenticatedScenariosMacrosRoute: AuthenticatedScenariosMacrosRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAgentPanelRoute: AuthenticatedSettingsAgentPanelRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedScenariosIndexRoute: AuthenticatedScenariosIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedIntegrationsFrontInboxesRoute:
    AuthenticatedIntegrationsFrontInboxesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountManagementRoute: AccountManagementRoute,
  StartRoute: StartRoute,
  AuthSlugRoute: AuthSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
